### ISSUE TITLE
Allow liquid objects within markdown

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [emanuelen5/vim-jekyll-syntax#2]
Hi! Thanks for this, it works nicely :)

One issue: to get the liquid syntax working in markdown files, I had to add the following two lines:
```
syntax cluster mkdNonListItem add=liquidObject
syntax cluster mkdNonListItem add=liquidTag
```

Without this, the markdown doesn't accept liquid objects: it only works at the start of the file, but not later on.

**Comment by emanuelen5** [comment]
Would you mind making a pull request with the change? I'd be happy to test it and merge it 🙂
